version: 1
services:
  - name: client
    buildCommand: docker-compose build --no-cache client
    startCommand: docker-compose up -d client
    healthCheckPath: /
    httpPort: 3000
    dockerfilePath: Dockerfile.client
    buildDirectory: .
  - name: server
    buildCommand: docker-compose build --no-cache server
    startCommand: docker-compose up -d server
    healthCheckPath: /ping
    httpPort: 5000
    dockerfilePath: Dockerfile.server
    buildDirectory: .
